id: I583F5EE8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-12T16:04:13+00:00'
last_modified: '2022-06-15T16:22:16.478552+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W923
  title: དྲང་ངེས་ལེགས་བཤད་སྙིང་པོའི་བརྒལ་ལན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4E1C:
      image_group_id: I1KG8924
      title: Volume 1 of drang nges legs bshad snying po'i brgal lan
      total_pages: 118
      order: 1
      base_file: 4E1C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
