id: I583F5EE8
legacy_id: P000317
ocr_import_info:
  bdrc_scan_id: W923
  source: bdrc
  ocr_info:
    timestamp: '2020-03-12T16:03:58'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T05:09:50.437743+00:00'
last_modified: 2022-09-04 13:09:54.926601
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W923
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW923
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དྲང་ངེས་ལེགས་བཤད་སྙིང་པོའི་བརྒལ་ལན།
  author: པཎ་ཆེན་བསོད་ནམས་གྲགས་པ།
statistics: null
quality: null
bases:
  I1KG8924:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8924
      total_pages: 118
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG8924.txt
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
